[package]
name = "kek"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = { version = "0.3.21", features = ["thread-pool"] }
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1.9", features = ["net"] }
hyper = { version = "0.14.20", features = ["full"] }
